# Generated by Django 4.0.5 on 2022-06-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('materiales', models.FloatField(default=0)),
                ('uso_energia', models.FloatField(default=0)),
                ('bateria', models.FloatField(default=0)),
                ('final_vida', models.FloatField(default=0)),
                ('embalaje', models.FloatField(default=0)),
                ('corporativo', models.FloatField(default=0)),
                ('fabricacion', models.FloatField(default=0)),
            ],
        ),
    ]
