# Generated by Django 4.0.5 on 2022-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coeficiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales', models.FloatField(default=1)),
                ('uso_energia', models.FloatField(default=1)),
                ('bateria', models.FloatField(default=1)),
                ('final_vida', models.FloatField(default=1)),
                ('embalaje', models.FloatField(default=1)),
                ('corporativo', models.FloatField(default=1)),
                ('fabricacion', models.FloatField(default=1)),
            ],
        ),
    ]
